[tool.poetry]
name = "hw2"
version = "0.1.0"
description = ""
authors = ["Konstantin Vesnin <kavesnin@edu.hse.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
latexlib-kavesnin = "^0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
